import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'
import {getSession} from 'next-auth/react'


export default function Home() {
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Biblioteca Joaquim Alves</h1>
        <div className={styles.logo}>
          <Image src='/../public/assets/logoJA.png' alt='logoJA' width={170} height={160} style={{ objectFit: 'cover' }}></Image>
        </div>
        <h3> Bem vindo!</h3>
        <Link href='/Login/Aluno'>
          <div className={styles.btn_login}> Sou aluno </div>
        </Link>
        <Link href={'/Login/Admin'}>
          <div className={styles.btn_login}> Acesso Admin</div>
        </Link>

      </main>
    </div>
  )
}
export async function getServerSideProps(context:any){
  const session = await getSession(context)
  if(session?.user?.email?.includes('@prof.ce.gov.br')||session?.user?.email?.includes('@aluno.ce.gov.br')){
    return {
      redirect:{
        destination:'/dashboard',
        permanent:false
      }
    }
   
  }else{
    return{
      props:{
        message:'usuario desconectado'
      }
    }
   }
  
}